- name: install necessary tool libpcre3 
  become: yes
  apt: name=libpcre3 state=present
  
- name: install necessary tool libpcre3-dev 
  become: yes
  apt: name=libpcre3-dev state=present
  
- name: install necessary tool zlib1g-dev 
  become: yes
  apt: name=zlib1g-dev state=present

- name: get source nginx
  become: yes
  become_user: vagrant
  get_url: url="http://nginx.org/download/nginx-1.13.12.tar.gz" dest="/home/vagrant/"

- name: unzip file
  become: yes
  become_user: vagrant
  unarchive: src="/home/vagrant/nginx-1.13.12.tar.gz" dest="/home/vagrant/" remote_src=yes

- name: configure nginx
  become: yes
  become_user: vagrant
  command: >
    {{ item }}
    chdir=/home/vagrant/nginx-1.13.12/
  with_items:
    - './configure --prefix=/usr/local/nginx/'
    - 'make'
    - 'sudo make install'

