var:
  nginx_pgp_url: http://nginx.org/keys/nginx_signing.key
  nginx_repository_url: http://nginx.org/packages/ubuntu/

- name : Add official nginx PGP key
  become: yes
  apt_key: url={{nginx_pgp_url}} state=present
  
- name : Add official nginx repository
  become: yes
  lineinfile : >
  dest=/etc/apt/sources.list
  line='{{item}} {{nginx_repository_url}} {{ansible_distribution_release}} nginx'
  with_items:
    - deb
    - deb-src
    
- name : Run apt-get update
  become: yes
  apt: update_cache=yes
  
- name : Install nginx
  become: yes
  apt : name=nginx state=present
