- name: install necessary tool that is bison
  become: yes
  apt: name=bison state=present

- name: install necessary tool that is redis
  become: yes
  become_user: shivashin
  get_url: url="http://download.redis.io/releases/redis-2.8.18.tar.gz" dest="/home/shivashin/"

- name: unzip redis file
  become: yes
  become_user: shivashin
  unarchive: src="/home/shivashin/redis-2.8.18.tar.gz" dest="/home/shivashin/" remote_src=yes

- name: redis make
  become: yes
  become_user: shivashin
  make: chdir="/home/shivashin/redis-2.8.18/"

- name: redis make install
  become: yes
  become_user: shivashin
  make: chdir="/home/shivashin/redis-2.8.18/"
  target: install

- name: install hiredis
  become: yes
  become_user: shivashin
  git:
    repo: https://github.com/redis/hiredis.git
    dest: /home/shivashin/hiredis
    remote: upstream
    
- name: hiredis make
  become: yes
  become_user: shivashin
  make: chdir="/home/shivashin/hiredis/"

- name: hiredis make install
  become: yes
  become_user: shivashin
  make: chdir="/home/shivashin/hiredis/"
  target: install

- name: install ngx_mruby
  become: yes
  become_user: shivashin
  git:
    repo: git://github.com/matsumoto-r/ngx_mruby.git
    dest: /home/shivashin/ngx_mruby
    remote: upstream
  ignore_errors: yes

- name: run script to build
  become: yes
  # become_user: shivashin
  command: >
    {{ item }}
    chdir=/home/shivashin/ngx_mruby/
  with_items:
    - "sudo NGINX_CONFIG_OPT_ENV='--prefix=/usr/local/nginx' NGINX_SRC_ENV='/home/shivashin/nginx-1.13.12' sh build.sh"
