- name: install necessary tool that is bison
  become: yes
  apt: name=bison state=present

- name: install necessary tool that is redis
  become: yes
  become_user: vagrant
  get_url: url="http://download.redis.io/releases/redis-2.8.18.tar.gz" dest="/home/vagrant/"

- name: unzip redis file
  become: yes
  become_user: vagrant
  unarchive: src="/home/vagrant/redis-2.8.18.tar.gz" dest="/home/vagrant/" remote_src=yes

- name: redis make
  become: yes
  become_user: vagrant
  make: chdir="/home/vagrant/redis-2.8.18/"

- name: redis make install
  become: yes
  become_user: vagrant
  make: chdir="/home/vagrant/redis-2.8.18/"
  target: install

- name: install hiredis
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/redis/hiredis.git
    dest: /home/vagrant/hiredis
    remote: upstream
    
- name: hiredis make
  become: yes
  become_user: vagrant
  make: chdir="/home/vagrant/hiredis/"

- name: hiredis make install
  become: yes
  become_user: vagrant
  make: chdir="/home/vagrant/hiredis/"
  target: install

- name: install ngx_mruby
  become: yes
  become_user: vagrant
  git:
    repo: git://github.com/matsumoto-r/ngx_mruby.git
    dest: /home/vagrant/ngx_mruby
    remote: upstream
  ignore_errors: yes

- name: run script to build
  become: yes
  command: >
    {{ item }}
    chdir=/home/vagrant/ngx_mruby/
  with_items:
    - './configure --with-ngx-src-root=/home/vagrant/nginx-1.4.6'
    - 'make build_mruby'
    - 'make generate_gems_config'
