- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add java8 repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: install java8
  become: yes
  apt: name=oracle-java8-installer state=present update_cache=yes
