 - name: export
   become: yes
   become_user: {{ user }}
   command: >
     {{ item }}
     chdir=/home/{{ user }}/LuaJIT-2.0.5
   with_items:
     - 'export LUAJIT_LIB=/usr/local/lib/'
     - 'export JIT_INC=/usr/local/include/luajit-2.0/'
     - 'export LIBDRIZZLE_LIB=/usr/local/lib'
     - 'export LIBDRIZZLE_INC=/usr/local/include/libdrizzle-1.0'

 - name: build nginx
   become: yes
   become_user: {{ user }}
   command: >
     {{ item }}
     chdir=/usr/local/src/nginx-1.14.0
   with_items:
     - 'sudo ./configure --prefix=/usr/local/nginx \
        --with-ld-opt="-Wl, -rpath, /usr/local/lib" \
        --add-module=/usr/local/src/ngx_devel_kit-0.3.0/ \
        --add-module=/usr/local/src/lua-nginx-module-0.10.12/ \
        --add-module=/usr/local/src/drizzle-nginx-module-0.1.11 \
        --add-module=/usr/local/src/rds-json-nginx-module-0.15 \
        --with-debug \
        --with-http_ssl_module \
        --with-http_stub_status_module'
    - 'sudo make -j2'
    - 'sudo make install'
