 - name: export luajit
   shell: echo LUAJIT_LIB is $LUAJIT_LIB
   environment:
     LUAJIT_LIB: /usr/local/lib/

 - name: export jit
   shell: echo JIT_INC is $JIT_INC
   environment:
     JLUAJIT_LIBIT_INC: /usr/local/include/luajit-2.0/
     
 - name: export libdrizzle_lib
   shell: echo LIBDRIZZLE_LIB is $LIBDRIZZLE_LIB
   environment:
     LIBDRIZZLE_LIB: /usr/local/lib

 - name: export libdrizzle_inc
   shell: echo LIBDRIZZLE_INC is $LIBDRIZZLE_INC
   environment:
     LIBDRIZZLE_INC: /usr/local/include/libdrizzle-1.0

 - name: build nginx
   become: yes
   become_user: '{{ user }}'
   command: >
     {{ item }}
     chdir=/usr/local/src/nginx-1.14.0
   with_items:
     - 'sudo ./configure --prefix=/usr/local/nginx 
       --with-ld-opt=-Wl,-rpath,/usr/local/lib 
       --add-module=/usr/local/src/ngx_devel_kit-0.3.0/ 
       --add-module=/usr/local/src/lua-nginx-module-0.10.12 
       --add-module=/usr/local/src/drizzle-nginx-module-0.1.11 
       --add-module=/usr/local/src/rds-json-nginx-module-0.15 
       --with-debug --with-http_ssl_module 
       --with-http_stub_status_module'
     - 'sudo make -j2'
     - 'sudo make install'
